name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v4
        with:
          enable-cache: true

      - name: Rye dependencies
        run: rye sync

      - name: Formatting
        run: rye run format-check

      - name: Linting
        run: rye run lint

      - name: Pyright linting
        run: rye run typecheck

      - name: Run tests
        run: rye run test
